repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
