export enum ErrorCodes {
  INTERNAL_SERVER_ERROR = 1,
  UNPROCESSABLE_ENTITY,
  TOKEN_EXPIRED,
  TOKEN_VALIDATION_FAILED,
  ENTITY_NOT_FOUND,
  ACCESS_DENIED,
  DOMAIN_ALREADY_TAKEN,
  EMAIL_ALREADY_TAKEN,
  USER_ALREADY_MEMBER
}

export const SERVICE_TOKEN = "Service test_service_token";
